### ISSUE TITLE
如何绘制一个染色体比对到多个染色体？

### ISSUE THREAD

**Issue by LiYiyan-code** [YangJianshun/LINKVIEW#3]
你好，请问LINKVIEW是否能实现一个染色体同时比对到两个染色体上？像下图这样
![image](https://user-images.githubusercontent.com/86640110/137866916-92a6c15d-cd80-443b-b3c5-69696578c92c.png)

**Comment by YangJianshun** [comment]
首先，LINKVIEW 可以实现画图，不能做比对。你的意思应该是能否绘制一张图，这张图上面展示两条序列，下面展示一条序列。
这是可以实现的，LINKVIEW 可以通过 -k 参数指定一个布局文件，你可以在这个文件中设计你想要的布局。

LINKVIEW 已经不再维护，我建议你使用最近发布的 LINKVIEW2。参考这个文档进行安装和使用。 https://github.com/YangJianshun/LINKVIEW2/wiki



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LiYiyan-code ***@***.***&gt;
发送时间: 2021年10月19日 15:52
收件人: YangJianshun/LINKVIEW ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[YangJianshun/LINKVIEW] 如何绘制一个染色体比对到多个染色体？ (Issue #3)





 
你好，请问LINKVIEW是否能实现一个染色体同时比对到两个染色体上？像下图这样
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
